#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<EOF
Usage:
  bash scripts/run_gwas.sh \
    --group CA \
    --gemma /path/to/gemma \
    --bfile data/genotype/CA/CAID \
    --kfile results/CA/grm/CA.snp.all.matrix.cXX.txt \
    --cfile data/covariates/CA/c.txt \
    --outdir results/CA/GWAS_results \
    --phenos "meta14,meta40,meta57"

Required arguments:
  --group     Group name, e.g. CA or CT
  --gemma     Path to GEMMA executable
  --bfile     PLINK file prefix
  --kfile     Kinship matrix file generated by GEMMA
  --cfile     Covariate file
  --outdir    Output directory
  --phenos    Comma-separated phenotype names, ordered exactly as phenotype columns in GEMMA input

Optional arguments:
  --start-col Starting phenotype column index in GEMMA (default: 1)
EOF
}

GROUP=""
GEMMA=""
BFILE=""
KFILE=""
CFILE=""
OUTDIR=""
PHENOS=""
START_COL=1

while [[ $# -gt 0 ]]; do
  case "$1" in
    --group)
      GROUP="$2"
      shift 2
      ;;
    --gemma)
      GEMMA="$2"
      shift 2
      ;;
    --bfile)
      BFILE="$2"
      shift 2
      ;;
    --kfile)
      KFILE="$2"
      shift 2
      ;;
    --cfile)
      CFILE="$2"
      shift 2
      ;;
    --outdir)
      OUTDIR="$2"
      shift 2
      ;;
    --phenos)
      PHENOS="$2"
      shift 2
      ;;
    --start-col)
      START_COL="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "[ERROR] Unknown argument: $1"
      usage
      exit 1
      ;;
  esac
done

if [[ -z "$GROUP" || -z "$GEMMA" || -z "$BFILE" || -z "$KFILE" || -z "$CFILE" || -z "$OUTDIR" || -z "$PHENOS" ]]; then
  echo "[ERROR] Missing required arguments."
  usage
  exit 1
fi

mkdir -p "$OUTDIR"

IFS=',' read -r -a PHENO_NAMES <<< "$PHENOS"

echo "[INFO] Group      : $GROUP"
echo "[INFO] GEMMA      : $GEMMA"
echo "[INFO] BFILE      : $BFILE"
echo "[INFO] KFILE      : $KFILE"
echo "[INFO] CFILE      : $CFILE"
echo "[INFO] Output dir : $OUTDIR"
echo "[INFO] Traits     : ${#PHENO_NAMES[@]}"
echo "[INFO] Start col  : $START_COL"

for ((i=0; i<${#PHENO_NAMES[@]}; i++)); do
  col=$((START_COL + i))
  name="${PHENO_NAMES[$i]}"

  echo "[INFO] Running GWAS for column $col ($name)"

  "$GEMMA" \
    -bfile "$BFILE" \
    -lmm 1 \
    -k "$KFILE" \
    -c "$CFILE" \
    -n "$col" \
    -o "$name"

  if ls output/${name}.* >/dev/null 2>&1; then
    mv output/${name}.* "$OUTDIR"/
  else
    echo "[WARN] No output files found for trait: $name"
  fi
done

if [[ -d "output" ]]; then
  rmdir output 2>/dev/null || true
fi

echo "[INFO] GWAS finished for group $GROUP"
echo "[INFO] Results saved in: $OUTDIR"